[package]
name = "fltk"
version = "0.12.10"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Rust bindings for the FLTK GUI library"
repository = "https://github.com/MoAlyousef/fltk-rs"
documentation = "https://docs.rs/fltk"
keywords = ["gui", "ui", "widgets", "bindings", "graphics"]
categories = ["gui"]
readme = "../README.md"
license = "MIT"
exclude = ["/.github", "./examples"]

[lib]
name = "fltk"
path = "src/lib.rs"

[dependencies]
fltk-sys = { path = "../fltk-sys", version = "=0.12.10" }
fltk-derive = { path = "../fltk-derive", version = "=0.12.10" }
lazy_static = "^1.4.0"
bitflags = "^1.2.1"

[features]
default = []
fltk-shared = ["fltk-sys/fltk-shared"] # (Experimental) Builds a shared lib of fltk
use-ninja = ["fltk-sys/use-ninja"] # If you have ninja build installed, it builds faster than make or VS
system-fltk = ["fltk-sys/system-fltk"] # (Experimental) If you would like to use the installed fltk library, should be FLTK 1.4
system-libpng = ["fltk-sys/system-libpng"] # Uses the system libpng
system-libjpeg = ["fltk-sys/system-libjpeg"] # Uses the system libjpeg
system-zlib = ["fltk-sys/system-zlib"] # Uses the system zlib
legacy-opengl = ["fltk-sys/legacy-opengl"] # (Experimental) Support of Lagacy OpenGL
fltk-bundled = ["fltk-sys/fltk-bundled"] # Support for bundled versions of cfltk and fltk (requires curl and tar)
enable-glwindow = ["fltk-sys/enable-glwindow"] # Support for systems without OpenGL
no-images = ["fltk-sys/no-images"] # (Experimental) You can use this feature if your app doesn't use images to reduce binary size
no-pango = ["fltk-sys/no-pango"] # (Experimental and Linux only) You can use this if you don't need rtl or cjk unicode support
