version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/fltk"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/fltk-sys"
    schedule:
      interval: "daily"

