[package]
name = "fltk"
version = "0.1.0"
authors = ["MoAlyousef <may642_2000@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fltk"
path = "src/lib.rs"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 0

[dependencies]
fltk-sys = { path = "fltk-sys", version = "0.1.0" }
fltk-derive = { path = "fltk-derive", version = "0.1.0" }

[[example]]
name = "hello"

[[example]]
name = "button"

[[example]]
name = "calculator"

[[example]]
name = "editor"

[[example]]
name = "gallery"