[package]
name = "fltk"
version = "0.1.0"
authors = ["MoAlyousef <may642_2000@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fltk"
path = "src/lib.rs"

[dependencies]
fltk-sys = { path = "fltk-sys", version = "0.1.0" }
libc = "^0.2"

[[example]]
name = "hello"

[[example]]
name = "button"

[[example]]
name = "input"