[package]
name = "fltk"
version = "0.1.2"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Rust bindings for the FLTK GUI library"
repository = "https://github.com/MoAlyousef/fltk-rs"
keywords = ["gui", "bindings", "graphics"]
license = "MIT"

[lib]
name = "fltk"
path = "src/lib.rs"

[dependencies]
fltk-sys = { path = "fltk-sys", version = "0.1.0" }
fltk-derive = { path = "fltk-derive", version = "0.1.0" }

[[example]]
name = "hello"

[[example]]
name = "button"

[[example]]
name = "calculator"

[[example]]
name = "editor"

[[example]]
name = "gallery"