[package]
name = "fltk"
version = "0.2.6"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Rust bindings for the FLTK GUI library"
repository = "https://github.com/MoAlyousef/fltk-rs"
documentation = "https://docs.rs/fltk"
keywords = ["gui", "bindings", "graphics"]
readme = "README.md"
license = "MIT"

[lib]
name = "fltk"
path = "src/lib.rs"

[dependencies]
fltk-sys = { path = "fltk-sys", version = "^0.2.6" }
fltk-derive = { path = "fltk-derive", version = "^0.2.6" }

[[example]]
name = "hello"

[[example]]
name = "hello_button"

[[example]]
name = "button"

[[example]]
name = "counter"

[[example]]
name = "calculator"

[[example]]
name = "editor"

[[example]]
name = "gallery"

[[example]]
name = "terminal"

[[example]]
name = "paint"