[package]
name = "fltk-sys"
version = "0.2.8"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
build = "build.rs"
edition = "2018"
description = "Rust bindings for the FLTK GUI library"
repository = "https://github.com/MoAlyousef/fltk-rs"
keywords = ["gui", "bindings", "graphics"]
license = "MIT"

[lib]
name = "fltk_sys"
path = "src/lib.rs"

[build-dependencies]
cmake = "^0.1"

