[package]
name = "fltk-sys"
version = "0.8.0"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
build = "build.rs"
edition = "2018"
description = "Rust bindings for the FLTK GUI library"
repository = "https://github.com/MoAlyousef/fltk-rs"
keywords = ["gui", "bindings", "graphics"]
license = "MIT"

[lib]
name = "fltk_sys"
path = "src/lib.rs"

[dependencies]
libc = "0.2.74"

[build-dependencies]
cmake = "^0.1.44"

[features]
default = []
fltk-shared = []
use-ninja = []
system-fltk = []
system-libpng = []
system-libjpeg = []
system-zlib = []
legacy-opengl = []
fltk-bundled = []
enable-glwindow = []
cpp-testing = [] # for C++ testing

