[package]
name = "fltk-sys"
version = "0.1.0"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
build = "build.rs"
edition = "2018"

[lib]
name = "fltk_sys"
path = "src/lib.rs"

[build-dependencies]
cmake = "^0.1"

