[package]
name = "fltk-derive"
version = "0.1.0"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Rust bindings for the FLTK GUI library"
repository = "https://github.com/MoAlyousef/fltk-rs"
readme = "https://github.com/MoAlyousef/fltk-rs/blob/master/README.md"
keywords = ["gui", "bindings", "graphics"]

[lib]
name = "fltk_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "^1.0.7"
quote = "^1.0.2"
