[package]
name = "fltk-derive"
version = "0.1.0"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"

[lib]
name = "fltk_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "^1.0.7"
quote = "^1.0.2"
