blank_issues_enabled: false
contact_links:
  - name: fltk-rs discussions
    url: https://github.com/fltk-rs/fltk-rs/discussions
    about: Please ask and answer questions here about fltk-rs specifically.
  - name: FLTK mailing list
    url: https://groups.google.com/g/fltkgeneral
    about: Please ask and answer questions here about FLTK in general.
