name: Release


on:
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-10.15, ubuntu-18.04]
    
    steps:
    - name: Download deps
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev
         fi
      shell: bash
    - name: xcode-select
      run: |
         if [ "$RUNNER_OS" == "macOS" ]; then
          sudo xcode-select -s /Applications/Xcode_11.3.app/Contents/Developer
         fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lib_${{ matrix.os }}
        path: target/release/build/**/out/lib
